module.exports = [
  {
    name: 'dashboard',
    mname: 'Dashboard',
    position: 0,
    href: '/dashboard',
  },
  {
    name: 'properties',
    mname: 'Properties',
    position: 1,
    href: '/properties',
  },
  {
    name: 'channels',
    mname: 'Channels',
    position: 2,
    href: '/channels',
  },
  {
    name: 'library',
    mname: 'Library',
    position: 3,
    href: '/library',
  },
  {
    name: 'batch',
    mname: 'Batch',
    position: 4,
    href: '/batch',
  },
  {
    name: 'categories',
    mname: 'Categories',
    position: 5,
    href: '/categories',
  },
  {
    name: 'stars',
    mname: 'Artists',
    position: 6,
    href: '/stars',
  },
  {
    name: 'users',
    mname: 'Users',
    position: 7,
    href: '/users',
  },
  {
    name: 'settings',
    mname: 'Settings',
    position: 8,
    href: '/settings',
  },
  {
    name: 'studio',
    mname: 'Studio',
    position: 9,
    href: '/studios',
  },
  {
    name: 'analytics',
    mname: 'Analytics',
    position: 10,
    href: '/analytics',
  },
  {
    name: 'livetv',
    mname: 'Livetv',
    position: 11,
    href: '/livetv',
  },
  {
    name: 'promotion',
    mname: 'Promotion',
    position: 12,
    href: '/promotion',
  },
  {
    name: 'emails',
    mname: 'Emails',
    position: 13,
    href: '/emails',
  },
  {
    name: 'blog',
    mname: 'Blog',
    position: 14,
    href: '/blog',
  },
  {
    name: 'promocode',
    mname: 'PromoCode',
    position: 15,
    href: '/promoCode',
  },
  {
    name: 'reports',
    mname: 'Reports',
    position: 16,
    href: '/reports',
  },
  {
    name: 'merch',
    mname: 'Merch',
    position: 17,
    href: '/merch',
  },
  {
    name: 'newsletters',
    mname: 'Newsletters',
    position: 18,
    href: '/newsletters',
  },
  {
    name: 'seo',
    mname: 'Seo',
    position: 19,
    href: '/seo',
  },
  {
    name: 'subscribers',
    mname: 'Subscribers',
    position: 20,
    href: '/subscribers',
  },
  {
    name: 'redirects',
    mname: 'Redirects',
    position: 21,
    href: '/redirects',
  },
  {
    name: 'pushes',
    mname: 'Pushes',
    position: 22,
    href: '/pushes',
  },
  {
    name: 'packages',
    mname: 'Packages',
    position: 23,
    href: '/packages',
  },
  {
    name: 'tokens',
    mname: 'Tokens',
    position: 24,
    href: '/tokens',
  },
  {
    name: 'clothes',
    mname: 'Clothes',
    position: 25,
    href: '/clothes',
  },
  {
    name: 'permissions',
    mname: 'Permissions',
    position: 26,
    href: '/permissions',
  },
  {
    name: 'animations',
    mname: 'Animations',
    position: 27,
    href: '/animations',
  },
  {
    name: 'rides',
    mname: 'Rides',
    position: 28,
    href: '/rides',
  },
  {
    name: 'feed',
    mname: 'Feed',
    position: 29,
    href: '/feed',
  },
];
